<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{86261e5a-b529-4817-93a2-323b76b5469b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TrafficLgiht();
Convert();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="34" Count="0" />
      <LineId Id="40" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>